export const commentsData = [
  {
    id: 1,
    user: "Ali Khan",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    text: "This video changed my perspective! 🔥",
    timestamp: "2 hours ago",
    likes: 120,
    dislikes: 3,
    replies: [
      {
        id: 2,
        user: "Sara Ahmed",
        avatar: "https://randomuser.me/api/portraits/women/2.jpg",
        text: "Same here! The storytelling was next level. 👏",
        timestamp: "1 hour ago",
        likes: 50,
        dislikes: 1,
        replies: [
          {
            id: 3,
            user: "Usman Raza",
            avatar: "https://randomuser.me/api/portraits/men/3.jpg",
            text: "I loved the editing style. Smooth transitions! 🎬",
            timestamp: "45 minutes ago",
            likes: 30,
            dislikes: 0,
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    user: "Bilal Qureshi",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    text: "Anyone knows which camera was used? The quality is insane! 🎥",
    timestamp: "50 minutes ago",
    likes: 22,
    dislikes: 0,
    replies: [
      {
        id: 5,
        user: "Ali Khan",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg",
        text: "I think they used a Sony A7S III with a 24-70mm lens. 🔍",
        timestamp: "40 minutes ago",
        likes: 10,
        dislikes: 0,
        replies: [],
      },
    ],
  },
  {
    id: 6,
    user: "Hina Shah",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    text: "Does anyone know the background music at 5:23? 🎶",
    timestamp: "3 hours ago",
    likes: 85,
    dislikes: 2,
    replies: [
      {
        id: 7,
        user: "Zeeshan Malik",
        avatar: "https://randomuser.me/api/portraits/men/7.jpg",
        text: "It's 'Lost in Thoughts' by Kevin MacLeod. Great choice! 🎼",
        timestamp: "2 hours ago",
        likes: 40,
        dislikes: 0,
        replies: [
          {
            id: 8,
            user: "Hina Shah",
            avatar: "https://randomuser.me/api/portraits/women/6.jpg",
            text: "Thanks a lot! Sounds so peaceful. 😊",
            timestamp: "1 hour ago",
            likes: 15,
            dislikes: 0,
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: 9,
    user: "Farhan Ali",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    text: "One of the best tutorials I've ever watched. Thank you! 🙌",
    timestamp: "5 hours ago",
    likes: 200,
    dislikes: 5,
    replies: [
      {
        id: 10,
        user: "Ayesha Noor",
        avatar: "https://randomuser.me/api/portraits/women/9.jpg",
        text: "100% agreed! Everything was explained so well. ✅",
        timestamp: "4 hours ago",
        likes: 90,
        dislikes: 1,
        replies: [
          {
            id: 11,
            user: "Usman Raza",
            avatar: "https://randomuser.me/api/portraits/men/3.jpg",
            text: "I wish more tutorials were this detailed. Huge respect! 🙏",
            timestamp: "3 hours ago",
            likes: 60,
            dislikes: 0,
            replies: [
              {
                id: 12,
                user: "Bilal Qureshi",
                avatar: "https://randomuser.me/api/portraits/men/5.jpg",
                text: "Yeah! Most tutorials skip the important details. 😅",
                timestamp: "2 hours ago",
                likes: 30,
                dislikes: 1,
                replies: [
                  {
                    id: 13,
                    user: "Farhan Ali",
                    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
                    text: "Right? The step-by-step breakdown really helped. 🙏",
                    timestamp: "1 hour ago",
                    likes: 20,
                    dislikes: 0,
                    replies: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 14,
    user: "Nadia Karim",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    text: "This deserves way more views! YouTube algorithm, do your thing. 🚀",
    timestamp: "6 hours ago",
    likes: 150,
    dislikes: 4,
    replies: [
      {
        id: 15,
        user: "Saad Rehman",
        avatar: "https://randomuser.me/api/portraits/men/11.jpg",
        text: "Exactly! More people need to see this masterpiece. 👏",
        timestamp: "5 hours ago",
        likes: 70,
        dislikes: 1,
        replies: [],
      },
    ],
  },
  {
    id: 16,
    user: "Zara Fatima",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    text: "Who's watching this in 2025? 😂",
    timestamp: "7 hours ago",
    likes: 300,
    dislikes: 7,
    replies: [
      {
        id: 17,
        user: "Hassan Ali",
        avatar: "https://randomuser.me/api/portraits/men/13.jpg",
        text: "Me! This video is still gold! 🏆",
        timestamp: "6 hours ago",
        likes: 110,
        dislikes: 2,
        replies: [],
      },
    ],
  },
];
